version: '3.9'
x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '1'
  driver: json-file

services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.2.1
    ports:
      - "9092:9092"
    volumes:
      - "kafka-data:/bitnami/kafka"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      ### CTBC config
      #- KAFKA_CFG_FETCH_MAX_WAIT_MS
      #- KAFKA_CFG_FETCH_MIN_BYTES
      #- KAFKA_CFG_FETCH_MAX_BYTES
      #- KAFKA_CFG_MAX_PARTITION_FETCH_BYTES
      #- KAFKA_CFG_AUTO_COMMIT_INTERVAL_MS
      - KAFKA_CFG_ENABLE.AUTO.COMMIT=false
      - KAFKA_CFG_ENABLE.IDEMPOTENCE=true
      #- KAFKA_CFG_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION
      - KAFKA_CFG_REQUIRED_ACKS=all
      #- KAFKA_CFG_RETRIES
      - KAFKA_CFG_ISOLATION_LEVEL=read_committed
      - KAFKA_CFG_HEARTBEAT_INTERVAL_MS=3000
      - KAFKA_CFG_SESSION_TIMEOUT_MS=10000
      - KAFKA_CFG_AUTO_OFFSET_RESET=earliest
      - KAFKA_CFG_MAX_PARTITION_FETCH_BYTES=1048576
      # KAFKA_CFG_GROUP_INSTANCE_ID=UNIQUE-ID
      ### Enable Auth
      #- KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SASL_SSL
      #- KAFKA_CFG_LISTENERS=INTERNAL://:9093,CLIENT://:9092
      #- KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,CLIENT://kafka:9092
      #- KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      #- KAFKA_CLIENT_USERS=${KAFKA_CLIENT_USERS:-kafka}    
      #- KAFKA_CLIENT_PASSWORDS=${KAFKA_CLIENT_PASSWORDS:-mypassword}                           
    depends_on:
      - zookeeper

networks:
  default:
    name: ${SANDBOX_PROJECT}
volumes:
  zookeeper-data: {}
  kafka-data: {}